from decimal import Decimal

CHIKN_RARITY_LIST = [
    "UNIQUE",
    "LEGENDARY",
    "ELITE",
    "RARE",
    "NICE",
    "COMMON",
]

FARMLAND_TILE_DICT = {
    "pyramid_Annuit": {
        "name": "Annuit Cœptis",
        "chance": 0.00148038490007402,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Pyramid_B_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Pyramid_B_0000.png",
        "resources": [{"name": "Dark Matter", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "pyramid_Avax": {
        "name": "AVAX Pyramid",
        "chance": 0.00148038490007402,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Pyramid_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Pyramid_A_0000.png",
        "resources": [{"name": "Avaxium", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "BoneDaddy": {
        "name": "Bone Daddy",
        "chance": 0.00148038490007402,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_BoneDaddy_0003.png",
        "image": "/api/farmland/tiles/image/Farmland_05_BoneDaddy_0003.png",
        "resources": [{"name": "Gold", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Goldmine": {
        "name": "Abandoned Mine",
        "chance": 0.00296076980014804,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Goldmine_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Goldmine_0000.png",
        "resources": [{"name": "Gold", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "ChiknMountain": {
        "name": "chikn Mountain",
        "chance": 0.00296076980014804,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_ChiknMountain_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_ChiknMountain_0000.png",
        "resources": [{"name": "Mana", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "Excalibur": {
        "name": "Excalibur",
        "chance": 0.00296076980014804,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Excalibur_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Excalibur_0000.png",
        "resources": [{"name": "Tungsten", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Meteor": {
        "name": "Space Rock",
        "chance": 0.00296076980014804,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Meteor_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Meteor_0000.png",
        "resources": [{"name": "Dark Matter", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Tungsten": {
        "name": "Tungsten Cube",
        "chance": 0.00296076980014804,
        "rarity": "Legendary",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Tungsten_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Tungsten_0000.png",
        "resources": [{"name": "Tungsten", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Ruin": {
        "name": "Ancient Ruins",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Ruin_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Ruin_A_0000.png",
        "resources": [{"name": "Mana", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "Red_Windmill": {
        "name": "Big Red Windmill",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Windmill_B_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Windmill_B_0000.png",
        "resources": [{"name": "Avaxium", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Golf": {
        "name": "Birdie",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Golf_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Golf_0000.png",
        "resources": [{"name": "Avaxium", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Graveyard": {
        "name": "Haunted Graveyard",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Graveyard_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Graveyard_0000.png",
        "resources": [{"name": "Gold", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "HelicopterPad": {
        "name": "Helipad",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_HelicopterPad_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_HelicopterPad_0000.png",
        "resources": [{"name": "Gold", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Mountain_Crystal": {
        "name": "Mana Mountain",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Mountain_Crystal_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Mountain_Crystal_0000.png",
        "resources": [{"name": "Mana", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "BigHole": {
        "name": "Mysterious Hole",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_BigHole_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_BigHole_0000.png",
        "resources": [{"name": "Dark Matter", "chance": Decimal(0.55), "fertilizing_bonus": Decimal(0.1), "fert_cost": 5000}],
    },
    "Old_Windmill": {
        "name": "Old Windmill",
        "chance": 0.00592153960029608,
        "rarity": "Elite",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Windmill_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Windmill_A_0000.png",
        "resources": [{"name": "Mech", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "Water": {
        "name": "Water",
        "chance": 0.00888230940044412,
        "rarity": "Rare",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Water_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Water_A_0000.png",
        "resources": [{"name": "Liquidium", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "SmallFarm_Wheat_Fence": {
        "name": "Fenced Feed Patch",
        "chance": 0.0118430792005922,
        "rarity": "Rare",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_SmallFarm_Wheat_Fence_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_SmallFarm_Wheat_Fence_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Mountain": {
        "name": "Mountain",
        "chance": 0.0118430792005922,
        "rarity": "Rare",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Mountain_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Mountain_0000.png",
        "resources": [{"name": "Mech", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "Pond_Circle": {
        "name": "Quaint Pond",
        "chance": 0.0118430792005922,
        "rarity": "Rare",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Pond_Circle_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Pond_Circle_0000.png",
        "resources": [{"name": "Liquidium", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "Pond_Corner": {
        "name": "Rock Pool",
        "chance": 0.0118430792005922,
        "rarity": "Rare",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Pond_Corner_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Pond_Corner_0000.png",
        "resources": [{"name": "Liquidium", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "Corn": {
        "name": "Bitcorn",
        "chance": 0.0236861584011843,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Corn_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Corn_A_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "SmallFarm_Corn": {
        "name": "Bitcorn Patch",
        "chance": 0.0236861584011843,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Corn_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Corn_A_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "SmallFarm_Corn_Fence": {
        "name": "Fenced Bitcorn Patch",
        "chance": 0.0236861584011843,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Corn_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Corn_A_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "SmallFarm_Cabbage": {
        "name": "Cabbage Patch",
        "chance": 0.0296076980014804,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_SmallFarm_Cabbage_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_SmallFarm_Cabbage_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "SmallFarm_Cabbage_Fence": {
        "name": "Fenced Cabbage Patch",
        "chance": 0.0296076980014804,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_SmallFarm_Cabbage_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_SmallFarm_Cabbage_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "SmallFarm_Empty": {
        "name": "Empty Patch",
        "chance": 0.0296076980014804,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_SmallFarm_Empty_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_SmallFarm_Empty_0000.png",
        "resources": [{"name": "Mech", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "Grass_Mushrooms": {
        "name": "Fairy Ring",
        "chance": 0.0296076980014804,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Grass_Mushrooms_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Grass_Mushrooms_0000.png",
        "resources": [{"name": "Mana", "chance": Decimal(0.60), "fertilizing_bonus": Decimal(0.1), "fert_cost": 3000}],
    },
    "SmallFarm_Wheat": {
        "name": "Feed Patch",
        "chance": 0.0296076980014804,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_SmallFarm_Wheat_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_SmallFarm_Wheat_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Wheat": {
        "name": "Wheat",
        "chance": 0.0296076980014804,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_SmallFarm_Wheat_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_SmallFarm_Wheat_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Woods": {
        "name": "Woodlands",
        "chance": 0.0355292376017764,
        "rarity": "Nice",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Woods_B_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Woods_B_0000.png",
        "resources": [{"name": "Lumber", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Roqs": {
        "name": "Roqs",
        "chance": 0.043079200592154,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Rocks_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Rocks_A_0000.png",
        "resources": [{"name": "Stone", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "CoqRoqs": {
        "name": "Coq Roqs",
        "chance": 0.0444115470022206,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Rocks_B_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Rocks_B_0000.png",
        "resources": [{"name": "Stone", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Tasty Feed": {
        "name": "Tasty Feed",
        "chance": 0.0473723168023686,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Wheat_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Wheat_A_0000.png",
        "resources": [{"name": "Veg", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Orchard": {
        "name": "Orchard",
        "chance": 0.0592153960029608,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Orchard_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Orchard_A_0000.png",
        "resources": [{"name": "Lumber", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Hills": {
        "name": "Rolling Hills",
        "chance": 0.0781643227239082,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Hills_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Hills_A_0000.png",
        "resources": [],
    },
    "Meadow": {
        "name": "Flower Meadow",
        "chance": 0.0781643227239082,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Meadow_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Meadow_A_0000.png",
        "resources": [],
    },
    "Grass_Trees": {
        "name": "Scattered Trees",
        "chance": 0.0781643227239082,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Grass_Trees_A_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Grass_Trees_A_0000.png",
        "resources": [{"name": "Lumber", "chance": Decimal(0.65), "fertilizing_bonus": Decimal(0.1), "fert_cost": 1500}],
    },
    "Grass_Full": {
        "name": "Healthy Lawn",
        "chance": 0.0888230940044412,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Grass_Full_01_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Grass_Full_01_0000.png",
        "resources": [],
    },
    "Grass_Thin": {
        "name": "Grass",
        "chance": 0.133234641006662,
        "rarity": "Common",
        "thumb": "/api/farmland/tiles/thumb/Farmland_05_Grass_Thin_01_0000.png",
        "image": "/api/farmland/tiles/image/Farmland_05_Grass_Thin_01_0000.png",
        "resources": [],
    },
}

FARMLAND_CSV_HEADER_ROW = [
    "ID",
    "Name",
    "Rarity",
    "Rarest Tile",
    "For Sale",
    "Sale Price",
    "# Unique Resources",
    "# Resources",
    "# Unique Tiles",
    "Dark Matter",
    "Avaxium",
    "Gold",
    "Mana",
    "Tungsten",
    "Mech",
    "Liquidium",
    "Veg",
    "Lumber",
    "Stone",
    "Last Price",
    "Bigness",
    "Size",
    "Fertility",
    "Multiplier",
    "Score",
    "Avg/Tile",
    "pyramid_Annuit",
    "pyramid_Avax",
    "BoneDaddy",
    "Goldmine",
    "ChiknMountain",
    "Excalibur",
    "Meteor",
    "Tungsten",
    "Ruin",
    "Red_Windmill",
    "Golf",
    "Graveyard",
    "HelicopterPad",
    "Mountain_Crystal",
    "BigHole",
    "Old_Windmill",
    "Water",
    "SmallFarm_Wheat_Fence",
    "Mountain",
    "Pond_Circle",
    "Pond_Corner",
    "Corn",
    "SmallFarm_Corn",
    "SmallFarm_Corn_Fence",
    "SmallFarm_Cabbage",
    "SmallFarm_Cabbage_Fence",
    "SmallFarm_Empty",
    "Grass_Mushrooms",
    "SmallFarm_Wheat",
    "Wheat",
    "Woods",
    "Roqs",
    "CoqRoqs",
    "Tasty Feed",
    "Orchard",
    "Hills",
    "Meadow",
    "Grass_Trees",
    "Grass_Full",
    "Grass_Thin",
]

"""
{
  x "token": 6337,
  x "forSale": false,
  x "salePrice": 9.91,
  "fertPerDay": 60,
  "kg": "28",
  "isRoosted": true,
  "name": null,
  "lore": null,
  "flavour": null,
  "rarity": "common",
  "head": "Chef",
  "neck": "",
  "torso": "",
  "feet": "Iron Claw",
  "tail": "",
  "body": "Snow White",
  "trim": "",
  "background": "Cornhusk",
  "_numOfTraits": 4,
  "rank": "10374",
  "score": 106.09,
  "floorPrice": 35
}


"""


ROOSTR_CSV_HEADER_ROW = [
    "ID",
    "Name",
    "KG",
    "For Sale",
    "Sale Price",
    "Fert/Day",
    "Rarity",
    "# Traits",
    "Rarest Trait",
    "Head",
    "Neck",
    "Torso",
    "Feet",
    "Tail",
    "Body",
    "Trim",
    "Background",
    "Lore",
    "Flavour",
    "Rank",
    "Score",
    "Floor Price",
    "Last Price",
    "Roosted",
]

ROOSTR_TRAIT_DICT = {
    "HEAD": {
        "?": {"rarity": "unique", "num_roostr": "72", "percentage": "0.10%"},
        "Boxhead": {"rarity": "legendary", "num_roostr": "72", "percentage": "0.32%"},
        "Hole in One": {"rarity": "legendary", "num_roostr": "40", "percentage": "0.33%"},
        "Smol Brain In Jar": {"rarity": "legendary", "num_roostr": "41", "percentage": "0.34%"},
        "Panic Buy": {"rarity": "legendary", "num_roostr": "41", "percentage": "0.34%"},
        "Robocoq": {"rarity": "legendary", "num_roostr": "41", "percentage": "0.35%"},
        "Green Party Hat": {"rarity": "legendary", "num_roostr": "43", "percentage": "0.36%"},
        "Bucket": {"rarity": "legendary", "num_roostr": "43", "percentage": "0.38%"},
        "Quarter Pounder": {"rarity": "legendary", "num_roostr": "47", "percentage": "0.39%"},
        "Feed Bag": {"rarity": "elite", "num_roostr": "48", "percentage": "0.40%"},
        "CRT": {"rarity": "elite", "num_roostr": "48", "percentage": "0.41%"},
        "Conspiracy Theorist": {"rarity": "elite", "num_roostr": "51", "percentage": "0.43%"},
        "Golden Templar": {"rarity": "elite", "num_roostr": "53", "percentage": "0.44%"},
        "Beaker": {"rarity": "elite", "num_roostr": "53", "percentage": "0.47%"},
        "Quarterback": {"rarity": "elite", "num_roostr": "53", "percentage": "0.53%"},
        "Plague Doctor": {"rarity": "elite", "num_roostr": "69", "percentage": "0.58%"},
        "Jell-O": {"rarity": "elite", "num_roostr": "69", "percentage": "0.62%"},
        "Golden Bone Daddy": {"rarity": "elite", "num_roostr": "78", "percentage": "0.65%"},
        "Gas Mask": {"rarity": "elite", "num_roostr": "91", "percentage": "0.76%"},
        "Hipster": {"rarity": "elite", "num_roostr": "91", "percentage": "0.84%"},
        "OASIS": {"rarity": "elite", "num_roostr": "91", "percentage": "0.84%"},
        "Batter-Up": {"rarity": "elite", "num_roostr": "91", "percentage": "0.91%"},
        "Templar": {"rarity": "elite", "num_roostr": "91", "percentage": "0.93%"},
        "SuperVillain": {"rarity": "elite", "num_roostr": "91", "percentage": "0.99%"},
        "Daffy": {"rarity": "rare", "num_roostr": "91", "percentage": "1.01%"},
        "Inherited Royalty": {"rarity": "rare", "num_roostr": "122", "percentage": "1.02%"},
        "Sombrero": {"rarity": "rare", "num_roostr": "122", "percentage": "1.08%"},
        "Rosebud": {"rarity": "rare", "num_roostr": "122", "percentage": "1.14%"},
        "Samurai": {"rarity": "rare", "num_roostr": "122", "percentage": "1.24%"},
        "Construction Helmet": {"rarity": "rare", "num_roostr": "188", "percentage": "1.57%"},
        "Chef": {"rarity": "rare", "num_roostr": "188", "percentage": "1.59%"},
        "Grandpa": {"rarity": "rare", "num_roostr": "188", "percentage": "1.59%"},
        "Chrome Dome": {"rarity": "rare", "num_roostr": "192", "percentage": "1.60%"},
        "Sunnies": {"rarity": "nice", "num_roostr": "192", "percentage": "1.60%"},
        "PermaBull": {"rarity": "nice", "num_roostr": "192", "percentage": "1.60%"},
        "Gentlechikn": {"rarity": "nice", "num_roostr": "192", "percentage": "1.64%"},
        "Mullet": {"rarity": "nice", "num_roostr": "192", "percentage": "1.64%"},
        "Woody": {"rarity": "nice", "num_roostr": "192", "percentage": "1.68%"},
        "Roodboi Rootie": {"rarity": "nice", "num_roostr": "202", "percentage": "1.69%"},
        "Coqpit Commander": {"rarity": "nice", "num_roostr": "203", "percentage": "1.69%"},
        "Snorkel": {"rarity": "nice", "num_roostr": "203", "percentage": "1.70%"},
        "Sesh Hat": {"rarity": "nice", "num_roostr": "206", "percentage": "1.72%"},
        "Beret": {"rarity": "nice", "num_roostr": "206", "percentage": "1.73%"},
        "Framez": {"rarity": "nice", "num_roostr": "206", "percentage": "1.75%"},
        "Hairy Old Man": {"rarity": "nice", "num_roostr": "212", "percentage": "1.77%"},
        "Coachella": {"rarity": "common", "num_roostr": "212", "percentage": "1.78%"},
        "Fez": {"rarity": "common", "num_roostr": "212", "percentage": "1.78%"},
        "Laser Eye": {"rarity": "common", "num_roostr": "219", "percentage": "1.83%"},
        "Happy Birthday": {"rarity": "common", "num_roostr": "223", "percentage": "1.86%"},
        "Dirty Bird": {"rarity": "common", "num_roostr": "223", "percentage": "1.86%"},
        "Beanie": {"rarity": "common", "num_roostr": "223", "percentage": "1.87%"},
        "Winterproof": {"rarity": "common", "num_roostr": "223", "percentage": "1.88%"},
        "Gentleman's Pipe": {"rarity": "common", "num_roostr": "227", "percentage": "1.90%"},
        "3D Specs": {"rarity": "common", "num_roostr": "233", "percentage": "1.95%"},
        "Cap": {"rarity": "common", "num_roostr": "233", "percentage": "2.05%"},
        "Golden Comb": {"rarity": "common", "num_roostr": "329", "percentage": "2.75%"},
        "Celestial Comb": {"rarity": "common", "num_roostr": "357", "percentage": "2.98%"},
        "Green Comb": {"rarity": "common", "num_roostr": "399", "percentage": "3.33%"},
        "Purple Comb": {"rarity": "common", "num_roostr": "408", "percentage": "3.41%"},
        "None": {"rarity": "common", "num_roostr": "408", "percentage": "24.02%"},
    },
    "NECK": {
        "?": {"rarity": "unique", "num_roostr": "408", "percentage": "0.10%"},
        "Floatie Boi": {"rarity": "legendary", "num_roostr": "38", "percentage": "0.32%"},
        "Avax Degen": {"rarity": "legendary", "num_roostr": "49", "percentage": "0.41%"},
        "Coq Maxi": {"rarity": "legendary", "num_roostr": "55", "percentage": "0.46%"},
        "Golden Pauldrons": {"rarity": "elite", "num_roostr": "101", "percentage": "0.84%"},
        "Gwei Guzzler": {"rarity": "elite", "num_roostr": "111", "percentage": "0.93%"},
        "Bitcoin Maxi": {"rarity": "elite", "num_roostr": "124", "percentage": "1.04%"},
        "Chick Magnet": {"rarity": "elite", "num_roostr": "239", "percentage": "2.00%"},
        "Clockchain": {"rarity": "elite", "num_roostr": "239", "percentage": "2.03%"},
        "Make a Wish": {"rarity": "elite", "num_roostr": "258", "percentage": "2.15%"},
        "Shoulder Armour": {"rarity": "rare", "num_roostr": "260", "percentage": "2.17%"},
        "Stop Loss": {"rarity": "rare", "num_roostr": "272", "percentage": "2.27%"},
        "Bone Necklace": {"rarity": "rare", "num_roostr": "275", "percentage": "2.30%"},
        "Joseph Drip": {"rarity": "rare", "num_roostr": "282", "percentage": "2.35%"},
        "Bandolier": {"rarity": "nice", "num_roostr": "282", "percentage": "2.43%"},
        "Coq Tags": {"rarity": "nice", "num_roostr": "412", "percentage": "3.44%"},
        "a little rag": {"rarity": "nice", "num_roostr": "420", "percentage": "3.51%"},
        "Lei": {"rarity": "nice", "num_roostr": "420", "percentage": "3.53%"},
        "Red Bowtie": {"rarity": "common", "num_roostr": "425", "percentage": "3.55%"},
        "Purple Bowtie": {"rarity": "common", "num_roostr": "428", "percentage": "3.57%"},
        "Sash": {"rarity": "common", "num_roostr": "428", "percentage": "3.58%"},
        "Prized Coq": {"rarity": "common", "num_roostr": "439", "percentage": "3.67%"},
        "Stethoscope": {"rarity": "common", "num_roostr": "439", "percentage": "3.76%"},
        "None": {"rarity": "common", "num_roostr": "439", "percentage": "49.61%"},
    },
    "TORSO": {
        "?": {"rarity": "unique", "num_roostr": "439", "percentage": "0.10%"},
        "Snib Snibs": {"rarity": "legendary", "num_roostr": "40", "percentage": "0.33%"},
        "Golden Breastplate": {"rarity": "legendary", "num_roostr": "47", "percentage": "0.39%"},
        "Midas Muscles": {"rarity": "legendary", "num_roostr": "48", "percentage": "0.40%"},
        "Doctor Coq": {"rarity": "legendary", "num_roostr": "48", "percentage": "0.40%"},
        "Dad Shirt": {"rarity": "legendary", "num_roostr": "57", "percentage": "0.48%"},
        "Snip Snips": {"rarity": "legendary", "num_roostr": "61", "percentage": "0.51%"},
        "Grande LeCoq": {"rarity": "legendary", "num_roostr": "63", "percentage": "0.53%"},
        "Kevlar": {"rarity": "elite", "num_roostr": "63", "percentage": "0.53%"},
        "Play Boy": {"rarity": "elite", "num_roostr": "67", "percentage": "0.56%"},
        "Gameboi": {"rarity": "elite", "num_roostr": "67", "percentage": "0.56%"},
        "Tweed": {"rarity": "elite", "num_roostr": "67", "percentage": "0.56%"},
        "Human Growth Hormones": {"rarity": "elite", "num_roostr": "72", "percentage": "0.60%"},
        "Black T-Shirt": {"rarity": "elite", "num_roostr": "87", "percentage": "0.73%"},
        "GoldFish": {"rarity": "elite", "num_roostr": "87", "percentage": "0.73%"},
        "White T-Shirt": {"rarity": "elite", "num_roostr": "91", "percentage": "0.76%"},
        "Red T-Shirt": {"rarity": "elite", "num_roostr": "93", "percentage": "0.78%"},
        "Breastplate": {"rarity": "elite", "num_roostr": "93", "percentage": "0.78%"},
        "Hendrix": {"rarity": "elite", "num_roostr": "93", "percentage": "0.86%"},
        "Floppy Disk": {"rarity": "elite", "num_roostr": "111", "percentage": "0.93%"},
        "Saddle": {"rarity": "elite", "num_roostr": "111", "percentage": "0.94%"},
        "Boombox": {"rarity": "elite", "num_roostr": "111", "percentage": "1.01%"},
        "McFly": {"rarity": "rare", "num_roostr": "111", "percentage": "1.09%"},
        "Banjo": {"rarity": "rare", "num_roostr": "111", "percentage": "1.20%"},
        "Not Football": {"rarity": "rare", "num_roostr": "151", "percentage": "1.26%"},
        "Bone": {"rarity": "rare", "num_roostr": "151", "percentage": "1.34%"},
        "Zippo": {"rarity": "rare", "num_roostr": "151", "percentage": "1.36%"},
        "Fancy Sword": {"rarity": "rare", "num_roostr": "171", "percentage": "1.43%"},
        "Rubber chikn": {"rarity": "rare", "num_roostr": "174", "percentage": "1.45%"},
        "Fresh Fish": {"rarity": "rare", "num_roostr": "175", "percentage": "1.46%"},
        "Lord Quas": {"rarity": "nice", "num_roostr": "187", "percentage": "1.56%"},
        "Katana": {"rarity": "nice", "num_roostr": "187", "percentage": "1.59%"},
        "Omelette": {"rarity": "nice", "num_roostr": "187", "percentage": "1.59%"},
        "Love Balloon": {"rarity": "nice", "num_roostr": "192", "percentage": "1.60%"},
        "Shield": {"rarity": "nice", "num_roostr": "192", "percentage": "1.60%"},
        "Home Run": {"rarity": "nice", "num_roostr": "194", "percentage": "1.62%"},
        "Hoops": {"rarity": "nice", "num_roostr": "194", "percentage": "1.65%"},
        "Avax Banger": {"rarity": "nice", "num_roostr": "202", "percentage": "1.69%"},
        "Gainz": {"rarity": "nice", "num_roostr": "202", "percentage": "1.73%"},
        "Banger": {"rarity": "nice", "num_roostr": "202", "percentage": "1.73%"},
        "Sword": {"rarity": "common", "num_roostr": "202", "percentage": "1.75%"},
        "Big Stick": {"rarity": "common", "num_roostr": "210", "percentage": "1.75%"},
        "CD-RW": {"rarity": "common", "num_roostr": "210", "percentage": "1.75%"},
        "Big Ol' Corn Cob": {"rarity": "common", "num_roostr": "215", "percentage": "1.79%"},
        "Starfish": {"rarity": "common", "num_roostr": "215", "percentage": "1.79%"},
        "Shovel": {"rarity": "common", "num_roostr": "215", "percentage": "1.83%"},
        "Spelunker": {"rarity": "common", "num_roostr": "215", "percentage": "1.84%"},
        "Spork": {"rarity": "common", "num_roostr": "215", "percentage": "1.85%"},
        "9-iron": {"rarity": "common", "num_roostr": "215", "percentage": "1.86%"},
        "The Key": {"rarity": "common", "num_roostr": "225", "percentage": "1.88%"},
        "A Fresh Baguette": {"rarity": "common", "num_roostr": "225", "percentage": "1.88%"},
        "Toot-Toot": {"rarity": "common", "num_roostr": "225", "percentage": "1.95%"},
        "None": {"rarity": "common", "num_roostr": "225", "percentage": "37.67%"},
    },
    "FEET": {
        "?": {"rarity": "unique", "num_roostr": "225", "percentage": "0.10%"},
        "Rugged": {"rarity": "legendary", "num_roostr": "225", "percentage": "1.05%"},
        "Golden Greaves": {"rarity": "legendary", "num_roostr": "158", "percentage": "1.32%"},
        "Red Stilettos": {"rarity": "elite", "num_roostr": "251", "percentage": "2.10%"},
        "Black Stilettos": {"rarity": "elite", "num_roostr": "256", "percentage": "2.14%"},
        "Greaves": {"rarity": "elite", "num_roostr": "256", "percentage": "2.35%"},
        "Blue Timbs": {"rarity": "elite", "num_roostr": "373", "percentage": "3.11%"},
        "Spurs": {"rarity": "elite", "num_roostr": "373", "percentage": "4.12%"},
        "Ball'n Chain": {"rarity": "rare", "num_roostr": "509", "percentage": "4.25%"},
        "All Stars": {"rarity": "rare", "num_roostr": "525", "percentage": "4.38%"},
        "Sneaker Head": {"rarity": "rare", "num_roostr": "530", "percentage": "4.42%"},
        "Iron Claw": {"rarity": "nice", "num_roostr": "532", "percentage": "4.44%"},
        "Buckaroo": {"rarity": "nice", "num_roostr": "532", "percentage": "4.48%"},
        "Croqs": {"rarity": "nice", "num_roostr": "532", "percentage": "4.55%"},
        "Golden Feet": {"rarity": "nice", "num_roostr": "678", "percentage": "5.66%"},
        "Celestial Feet": {"rarity": "common", "num_roostr": "692", "percentage": "5.78%"},
        "Green Feet": {"rarity": "common", "num_roostr": "807", "percentage": "6.74%"},
        "Red Feet": {"rarity": "common", "num_roostr": "830", "percentage": "6.93%"},
        "None": {"rarity": "common", "num_roostr": "830", "percentage": "32.08%"},
    },
    "TAIL": {
        "?": {"rarity": "unique", "num_roostr": "830", "percentage": "0.10%"},
        "Concorde": {"rarity": "legendary", "num_roostr": "830", "percentage": "0.30%"},
        "Scorpion King": {"rarity": "legendary", "num_roostr": "41", "percentage": "0.34%"},
        "Prawn Coqtail": {"rarity": "elite", "num_roostr": "41", "percentage": "0.34%"},
        "Hydra": {"rarity": "elite", "num_roostr": "41", "percentage": "0.35%"},
        "Peacoq": {"rarity": "elite", "num_roostr": "41", "percentage": "0.43%"},
        "WhaleGod": {"rarity": "elite", "num_roostr": "41", "percentage": "0.43%"},
        "Off Grid": {"rarity": "rare", "num_roostr": "68", "percentage": "0.57%"},
        "Sword Tail": {"rarity": "rare", "num_roostr": "71", "percentage": "0.59%"},
        "Big Mama Fat Pipes": {"rarity": "nice", "num_roostr": "72", "percentage": "0.60%"},
        "Royal Flush": {"rarity": "nice", "num_roostr": "76", "percentage": "0.63%"},
        "Foliage": {"rarity": "nice", "num_roostr": "76", "percentage": "0.75%"},
        "Smokestack": {"rarity": "common", "num_roostr": "76", "percentage": "1.76%"},
        "Gas Guzzler": {"rarity": "common", "num_roostr": "244", "percentage": "2.04%"},
        "chikn Jockey": {"rarity": "common", "num_roostr": "287", "percentage": "2.40%"},
        "None": {"rarity": "common", "num_roostr": "287", "percentage": "88.35%"},
    },
    "BODY": {
        "?": {"rarity": "unique", "num_roostr": "287", "percentage": "0.10%"},
        "Celestial": {"rarity": "legendary", "num_roostr": "287", "percentage": "1.56%"},
        "Bullion": {"rarity": "elite", "num_roostr": "287", "percentage": "3.19%"},
        "Obsidian": {"rarity": "elite", "num_roostr": "287", "percentage": "4.03%"},
        "Midnight": {"rarity": "rare", "num_roostr": "287", "percentage": "4.63%"},
        "Mutant Purple": {"rarity": "rare", "num_roostr": "1459", "percentage": "12.18%"},
        "Frog Green": {"rarity": "nice", "num_roostr": "1462", "percentage": "12.21%"},
        "Passion Red": {"rarity": "nice", "num_roostr": "1475", "percentage": "12.31%"},
        "Nightstalker Blue": {"rarity": "common", "num_roostr": "1536", "percentage": "12.82%"},
        "Snow White": {"rarity": "common", "num_roostr": "4428", "percentage": "36.97%"},
    },
    "TRIM": {
        "?": {"rarity": "unique", "num_roostr": "4428", "percentage": "0.10%"},
        "Space Trim": {"rarity": "legendary", "num_roostr": "41", "percentage": "0.34%"},
        "Atlantis Trim": {"rarity": "elite", "num_roostr": "71", "percentage": "0.59%"},
        "Vulcan Trim": {"rarity": "elite", "num_roostr": "73", "percentage": "0.61%"},
        "Avax Trim": {"rarity": "rare", "num_roostr": "334", "percentage": "2.79%"},
        "Blue Trim": {"rarity": "nice", "num_roostr": "341", "percentage": "2.85%"},
        "Black Trim": {"rarity": "common", "num_roostr": "350", "percentage": "2.92%"},
        "None": {"rarity": "common", "num_roostr": "350", "percentage": "89.80%"},
    },
    "BACKGROUND": {
        "?": {"rarity": "unique", "num_roostr": "350", "percentage": "0.10%"},
        "Field Glitch": {"rarity": "legendary", "num_roostr": "64", "percentage": "0.53%"},
        "Vaporwave Glitch": {"rarity": "legendary", "num_roostr": "66", "percentage": "0.55%"},
        "Farm Glitch": {"rarity": "legendary", "num_roostr": "68", "percentage": "0.57%"},
        "Galactic Glitch": {"rarity": "elite", "num_roostr": "72", "percentage": "0.60%"},
        "Galactic": {"rarity": "elite", "num_roostr": "72", "percentage": "0.97%"},
        "Vaporwave": {"rarity": "elite", "num_roostr": "72", "percentage": "0.97%"},
        "Vulcan": {"rarity": "elite", "num_roostr": "72", "percentage": "1.56%"},
        "Atlantis": {"rarity": "elite", "num_roostr": "72", "percentage": "1.61%"},
        "Drummies": {"rarity": "elite", "num_roostr": "72", "percentage": "2.48%"},
        "Farm": {"rarity": "rare", "num_roostr": "72", "percentage": "2.66%"},
        "Field": {"rarity": "rare", "num_roostr": "72", "percentage": "2.78%"},
        "Vibe": {"rarity": "rare", "num_roostr": "72", "percentage": "3.64%"},
        "Miami": {"rarity": "nice", "num_roostr": "72", "percentage": "3.75%"},
        "Venus": {"rarity": "nice", "num_roostr": "72", "percentage": "3.78%"},
        "Solana": {"rarity": "nice", "num_roostr": "72", "percentage": "3.79%"},
        "Royale": {"rarity": "nice", "num_roostr": "72", "percentage": "6.37%"},
        "Tangerine": {"rarity": "nice", "num_roostr": "72", "percentage": "7.05%"},
        "Vermillion": {"rarity": "common", "num_roostr": "72", "percentage": "7.84%"},
        "Plum": {"rarity": "common", "num_roostr": "72", "percentage": "11.01%"},
        "Turquoisey": {"rarity": "common", "num_roostr": "72", "percentage": "12.07%"},
        "Periwinkle": {"rarity": "common", "num_roostr": "72", "percentage": "12.30%"},
        "Cornhusk": {"rarity": "common", "num_roostr": "72", "percentage": "13.01%"},
    },
}


CHIKN_CSV_HEADER_ROW = [
    "ID",
    "Name",
    "KG",
    "For Sale",
    "Sale Price",
    "EGG/Day",
    "Rarity",
    "# Traits",
    "Rarest Trait",
    "Head",
    "Neck",
    "Torso",
    "Feet",
    "Tail",
    "Body",
    "Trim",
    "Background",
    "Lore",
    "Flavour",
    "Rank",
    "Score",
    "Floor Price",
    "Last Price",
    "Roosted",
]

CHIKN_TRAIT_DICT = {
    "HEAD": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.12%"},
        "daft punk": {"rarity": "legendary", "num_chikn": "26", "percentage": "0.36%"},
        "tungsten cube": {"rarity": "legendary", "num_chikn": "27", "percentage": "0.37%"},
        "golden bone daddy": {"rarity": "legendary", "num_chikn": "30", "percentage": "0.41%"},
        "boxhead": {"rarity": "legendary", "num_chikn": "38", "percentage": "0.52%"},
        "murica": {"rarity": "elite", "num_chikn": "42", "percentage": "0.58%"},
        "hamlet": {"rarity": "elite", "num_chikn": "51", "percentage": "0.70%"},
        "inherited royalty": {"rarity": "elite", "num_chikn": "53", "percentage": "0.73%"},
        "pineapple": {"rarity": "elite", "num_chikn": "57", "percentage": "0.78%"},
        "icey stare": {"rarity": "elite", "num_chikn": "59", "percentage": "0.81%"},
        "golden crusader": {"rarity": "elite", "num_chikn": "59", "percentage": "0.81%"},
        "super saiyan": {"rarity": "elite", "num_chikn": "73", "percentage": "1.00%"},
        "luckiest red cap": {"rarity": "elite", "num_chikn": "78", "percentage": "1.07%"},
        "laser eye": {"rarity": "rare", "num_chikn": "78", "percentage": "1.07%"},
        "goose": {"rarity": "rare", "num_chikn": "100", "percentage": "1.38%"},
        "cheeky redhead": {"rarity": "rare", "num_chikn": "104", "percentage": "1.43%"},
        "charcoal brunette": {"rarity": "rare", "num_chikn": "105", "percentage": "1.44%"},
        "saint": {"rarity": "rare", "num_chikn": "106", "percentage": "1.46%"},
        "smoking lounge": {"rarity": "rare", "num_chikn": "106", "percentage": "1.46%"},
        "mysterious fez": {"rarity": "rare", "num_chikn": "107", "percentage": "1.47%"},
        "all seeing eye": {"rarity": "rare", "num_chikn": "111", "percentage": "1.53%"},
        "gentlechikn": {"rarity": "rare", "num_chikn": "112", "percentage": "1.54%"},
        "hothead": {"rarity": "rare", "num_chikn": "112", "percentage": "1.54%"},
        "mfd": {"rarity": "nice", "num_chikn": "114", "percentage": "1.57%"},
        "avax safety officer": {"rarity": "nice", "num_chikn": "115", "percentage": "1.58%"},
        "frothy crown": {"rarity": "nice", "num_chikn": "116", "percentage": "1.60%"},
        "golden blonde": {"rarity": "nice", "num_chikn": "119", "percentage": "1.64%"},
        "low vision admiral": {"rarity": "nice", "num_chikn": "121", "percentage": "1.66%"},
        "crusader": {"rarity": "nice", "num_chikn": "146", "percentage": "2.01%"},
        "lucky blue cap": {"rarity": "nice", "num_chikn": "163", "percentage": "2.24%"},
        "construction helmet": {"rarity": "nice", "num_chikn": "217", "percentage": "2.98%"},
        "pixel cigarette": {"rarity": "nice", "num_chikn": "219", "percentage": "3.01%"},
        "red mage": {"rarity": "nice", "num_chikn": "221", "percentage": "3.04%"},
        "gentleman's pipe": {"rarity": "nice", "num_chikn": "224", "percentage": "3.08%"},
        "hubba bubba": {"rarity": "nice", "num_chikn": "227", "percentage": "3.12%"},
        "sucker": {"rarity": "common", "num_chikn": "229", "percentage": "3.15%"},
        "maverick": {"rarity": "common", "num_chikn": "229", "percentage": "3.15%"},
        "top of the morning": {"rarity": "common", "num_chikn": "231", "percentage": "3.18%"},
        "nerdlinger": {"rarity": "common", "num_chikn": "231", "percentage": "3.18%"},
        "blue mage": {"rarity": "common", "num_chikn": "233", "percentage": "3.20%"},
        "cool dude 69": {"rarity": "common", "num_chikn": "233", "percentage": "3.20%"},
        "black sweatband": {"rarity": "common", "num_chikn": "235", "percentage": "3.23%"},
        "savage beast": {"rarity": "common", "num_chikn": "240", "percentage": "3.30%"},
        "moustache": {"rarity": "common", "num_chikn": "241", "percentage": "3.31%"},
        "uniquehorn": {"rarity": "common", "num_chikn": "244", "percentage": "3.36%"},
        "deal with it": {"rarity": "common", "num_chikn": "246", "percentage": "3.38%"},
        "purple sweatband": {"rarity": "common", "num_chikn": "249", "percentage": "3.42%"},
        "covid safe": {"rarity": "common", "num_chikn": "253", "percentage": "3.48%"},
        "pillager": {"rarity": "common", "num_chikn": "259", "percentage": "3.56%"},
        "admiral": {"rarity": "common", "num_chikn": "273", "percentage": "3.75%"},
    },
    "NECK": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.15%"},
        "avax degen": {"rarity": "legendary", "num_chikn": "77", "percentage": "1.26%"},
        "mim og": {"rarity": "elite", "num_chikn": "82", "percentage": "1.34%"},
        "bitcoin maxi": {"rarity": "elite", "num_chikn": "84", "percentage": "1.37%"},
        "second head": {"rarity": "elite", "num_chikn": "85", "percentage": "1.39%"},
        "ethereum gwei guzzler": {"rarity": "rare", "num_chikn": "91", "percentage": "1.48%"},
        "blue bandana": {"rarity": "rare", "num_chikn": "221", "percentage": "3.60%"},
        "red bandana": {"rarity": "rare", "num_chikn": "243", "percentage": "3.96%"},
        "black bandana": {"rarity": "rare", "num_chikn": "276", "percentage": "4.50%"},
        "mim bling": {"rarity": "nice", "num_chikn": "302", "percentage": "4.92%"},
        "bitcoin bling": {"rarity": "nice", "num_chikn": "336", "percentage": "5.48%"},
        "chains for days": {"rarity": "nice", "num_chikn": "339", "percentage": "5.53%"},
        "dollar chain": {"rarity": "nice", "num_chikn": "341", "percentage": "5.56%"},
        "ethereum bling": {"rarity": "nice", "num_chikn": "350", "percentage": "5.71%"},
        "chicken choker": {"rarity": "common", "num_chikn": "367", "percentage": "5.98%"},
        "avax bling": {"rarity": "common", "num_chikn": "440", "percentage": "7.17%"},
        "wage slave": {"rarity": "common", "num_chikn": "459", "percentage": "7.48%"},
        "red bowtie": {"rarity": "common", "num_chikn": "599", "percentage": "9.77%"},
        "purple bowtie": {"rarity": "common", "num_chikn": "702", "percentage": "11.45%"},
        "hairy old man": {"rarity": "common", "num_chikn": "730", "percentage": "11.90%"},
    },
    "TORSO": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.16%"},
        "business boy": {"rarity": "legendary", "num_chikn": "49", "percentage": "0.90%"},
        "karate kid": {"rarity": "elite", "num_chikn": "75", "percentage": "1.37%"},
        "action shorts": {"rarity": "elite", "num_chikn": "127", "percentage": "2.32%"},
        "nugget wand": {"rarity": "elite", "num_chikn": "132", "percentage": "2.41%"},
        "midas muscles": {"rarity": "rare", "num_chikn": "139", "percentage": "2.54%"},
        "captain chimerica": {"rarity": "rare", "num_chikn": "151", "percentage": "2.76%"},
        "big bag of cash": {"rarity": "rare", "num_chikn": "178", "percentage": "3.25%"},
        "blue bag": {"rarity": "common", "num_chikn": "", "percentage": ""},
        "spell wand": {"rarity": "rare", "num_chikn": "178", "percentage": "3.25%"},
        "hentai": {"rarity": "nice", "num_chikn": "235", "percentage": "4.30%"},
        "popsicle": {"rarity": "nice", "num_chikn": "282", "percentage": "5.15%"},
        "cutlass": {"rarity": "nice", "num_chikn": "300", "percentage": "5.48%"},
        "fresh fish": {"rarity": "nice", "num_chikn": "334", "percentage": "6.10%"},
        "mighty broadsword": {"rarity": "nice", "num_chikn": "339", "percentage": "6.20%"},
        "human growth hormones": {"rarity": "common", "num_chikn": "353", "percentage": "6.45%"},
        "peacemaker": {"rarity": "common", "num_chikn": "492", "percentage": "8.99%"},
        "big ol corn cob": {"rarity": "common", "num_chikn": "509", "percentage": "9.30%"},
        "summer days": {"rarity": "common", "num_chikn": "525", "percentage": "9.60%"},
        "a fresh baguette": {"rarity": "common", "num_chikn": "529", "percentage": "9.67%"},
        "old fashioned romance": {"rarity": "common", "num_chikn": "535", "percentage": "9.78%"},
    },
    "FEET": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.09%"},
        "real feet": {"rarity": "legendary", "num_chikn": "98", "percentage": "0.98%"},
        "red leather boots": {"rarity": "elite", "num_chikn": "113", "percentage": "1.13%"},
        "swashbucklers": {"rarity": "elite", "num_chikn": "121", "percentage": "1.21%"},
        "purple leather boots": {"rarity": "rare", "num_chikn": "133", "percentage": "1.33%"},
        "comfortable uggs": {"rarity": "rare", "num_chikn": "134", "percentage": "1.34%"},
        "rollerderby": {"rarity": "rare", "num_chikn": "142", "percentage": "1.42%"},
        "green kicks": {"rarity": "rare", "num_chikn": "176", "percentage": "1.76%"},
        "red vans": {"rarity": "nice", "num_chikn": "203", "percentage": "2.03%"},
        "black vans": {"rarity": "nice", "num_chikn": "215", "percentage": "2.15%"},
        "blue kicks": {"rarity": "nice", "num_chikn": "289", "percentage": "2.89%"},
        "purple feet": {"rarity": "nice", "num_chikn": "1000", "percentage": "10.00%"},
        "red feet": {"rarity": "common", "num_chikn": "1024", "percentage": "10.24%"},
        "green feet": {"rarity": "common", "num_chikn": "1034", "percentage": "10.34%"},
        "blue feet": {"rarity": "common", "num_chikn": "1040", "percentage": "10.40%"},
        "none": {"rarity": "common", "num_chikn": "4273", "percentage": "42.71%"},
    },
    "TAIL": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.09%"},
        "big mama fat pipes": {"rarity": "legendary", "num_chikn": "184", "percentage": "1.84%"},
        "golden plumage": {"rarity": "elite", "num_chikn": "211", "percentage": "2.11%"},
        "golden egg": {"rarity": "rare", "num_chikn": "274", "percentage": "2.74%"},
        "gas guzzler": {"rarity": "rare", "num_chikn": "412", "percentage": "4.12%"},
        "orange plumage": {"rarity": "rare", "num_chikn": "588", "percentage": "5.88%"},
        "led": {"rarity": "nice", "num_chikn": "595", "percentage": "5.95%"},
        "red plumage": {"rarity": "nice", "num_chikn": "612", "percentage": "6.12%"},
        "nyan": {"rarity": "nice", "num_chikn": "747", "percentage": "7.47%"},
        "very fresh egg": {"rarity": "common", "num_chikn": "800", "percentage": "8.00%"},
        "liarliar": {"rarity": "common", "num_chikn": "825", "percentage": "8.25%"},
        "none": {"rarity": "common", "num_chikn": "4744", "percentage": "47.44%"},
    },
    "BODY": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.09%"},
        "celestial": {"rarity": "legendary", "num_chikn": "110", "percentage": "1.10%"},
        "crystalé": {"rarity": "elite", "num_chikn": "201", "percentage": "2.01%"},
        "bullion": {"rarity": "rare", "num_chikn": "252", "percentage": "2.52%"},
        "pixel-chan": {"rarity": "rare", "num_chikn": "516", "percentage": "5.16%"},
        "gameboy": {"rarity": "nice", "num_chikn": "554", "percentage": "5.54%"},
        "passion red": {"rarity": "nice", "num_chikn": "1511", "percentage": "15.11%"},
        "frognation green": {"rarity": "nice", "num_chikn": "1539", "percentage": "15.39%"},
        "nightstalker blue": {"rarity": "common", "num_chikn": "1546", "percentage": "15.46%"},
        "mutant purple": {"rarity": "common", "num_chikn": "1616", "percentage": "16.16%"},
        "rustic brown": {"rarity": "common", "num_chikn": "2147", "percentage": "21.47%"},
    },
    "TRIM": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.09%"},
        "cloud trim": {"rarity": "elite", "num_chikn": "180", "percentage": "1.80%"},
        "space trim": {"rarity": "rare", "num_chikn": "181", "percentage": "1.81%"},
        "black trim": {"rarity": "rare", "num_chikn": "285", "percentage": "2.85%"},
        "blue trim": {"rarity": "nice", "num_chikn": "393", "percentage": "3.93%"},
        "avax trim": {"rarity": "common", "num_chikn": "423", "percentage": "4.23%"},
        "none": {"rarity": "common", "num_chikn": "8529", "percentage": "85.29%"},
    },
    "BACKGROUND": {
        "?": {"rarity": "unique", "num_chikn": "9", "percentage": "0.09%"},
        "galactic": {"rarity": "legendary", "num_chikn": "53", "percentage": "0.53%"},
        "moon": {"rarity": "elite", "num_chikn": "128", "percentage": "1.28%"},
        "farm": {"rarity": "elite", "num_chikn": "173", "percentage": "1.73%"},
        "cloud": {"rarity": "elite", "num_chikn": "241", "percentage": "2.41%"},
        "nugget": {"rarity": "rare", "num_chikn": "369", "percentage": "3.69%"},
        "miami": {"rarity": "rare", "num_chikn": "428", "percentage": "4.28%"},
        "vibe": {"rarity": "rare", "num_chikn": "432", "percentage": "4.32%"},
        "solana": {"rarity": "nice", "num_chikn": "453", "percentage": "4.53%"},
        "venus": {"rarity": "nice", "num_chikn": "464", "percentage": "4.64%"},
        "tangerine": {"rarity": "nice", "num_chikn": "696", "percentage": "6.96%"},
        "periwinkle": {"rarity": "nice", "num_chikn": "712", "percentage": "7.12%"},
        "turquoisey": {"rarity": "common", "num_chikn": "723", "percentage": "7.23%"},
        "plum": {"rarity": "common", "num_chikn": "727", "percentage": "7.27%"},
        "royale": {"rarity": "common", "num_chikn": "743", "percentage": "7.43%"},
        "cornhusk": {"rarity": "common", "num_chikn": "1813", "percentage": "18.13%"},
        "vermillion": {"rarity": "common", "num_chikn": "1836", "percentage": "18.36%"},
    },
}
